name: bn-mobile-client

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL:-mongodb://localhost:27017/hijaiyah-app}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    ports:
      - "${CLIENT_PORT:-3000}:3000"
